--Todays date GETDATE FUNCTION 
SELECT GETDATE()

--DATEADD FUNCTION - ADD TIME INTERVAL TO THE DATE ARGUMENT 

 SELECT DATEADD (DD , 7 , GETDATE()) AS [NEXT WEEK]
 SELECT DATEADD (MM , 3 , GETDATE()) AS [11TH MONTH]
  SELECT DATEADD (YY , 1 , GETDATE()) AS [NEXT YEAR]

  --WEEK AGO
  SELECT GETDATE() -7
  SELECT DATEADD (DD , -7 , GETDATE()) AS [WEEK AGO]

  -- MONTH AGO
  SELECT GETDATE() -31
   SELECT DATEADD (MM , -1 , GETDATE()) AS [MONTH AGO]

--YEAR AGO
  SELECT GETDATE() -365
  SELECT DATEADD (YY , -1 , GETDATE()) AS [YEAR AGO]

  --DATEPART FUNCTION - RETURNS PART OF THE DATE IN CHARACTER FORMAT
	  SELECT DATEPART ( SS , GETDATE() )
	  SELECT DATEPART ( YY , GETDATE() )
	  SELECT DATEPART ( MM , GETDATE() )
	  SELECT DATEPART ( DD , GETDATE() )
	  SELECT DATEPART ( HH , GETDATE() )
	  SELECT DATEPART ( MI , GETDATE() )
	  SELECT DATEPART ( DY , GETDATE() )
	  SELECT DATEPART ( MS , GETDATE() )
	  SELECT DATEPART ( WK , GETDATE() )

	  --ANOTHER METHOD
	  SELECT DAY (  GETDATE() )
	  SELECT MONTH ( GETDATE() )
	  SELECT YEAR ( GETDATE() )